default: llc

llc:
	javac LinkedListCycle.java
	java LinkedListCycle

stock1:
	javac Stock1.java
	java Stock1

reverseinteger:
	javac ReverseInteger.java
	java ReverseInteger
	
sametree:
	javac SameTree.java
	java SameTree

maxdepth:
	javac MaxDepth.java
	java MaxDepth

singlenumber:
	javac SingleNumber.java
	java SingleNumber

wordbreak:
	javac WordBreak.java
	java WordBreak
