default: reverseinteger

reverseinteger:
	javac ReverseInteger.java
	java ReverseInteger
	
sametree:
	javac SameTree.java
	java SameTree

maxdepth:
	javac MaxDepth.java
	java MaxDepth

singlenumber:
	javac SingleNumber.java
	java SingleNumber

wordbreak:
	javac WordBreak.java
	java WordBreak
