default: removeduplicatesarray

climbstairs:
	javac ClimbingStairs.java
	java ClimbingStairs
	
symmetrictree:
	javac SymmetricTree.java
	java SymmetricTree

removeelement:
	javac RemoveElement.java
	java RemoveElement

removeduplicatesarray:
	javac RemoveDuplicatesFromSortedArray.java
	java RemoveDuplicatesFromSortedArray

removeduplicates:
	javac RemoveDuplicatesFromSortedList.java
	java RemoveDuplicatesFromSortedList

searchinsert:
	javac SearchInsertPosition.java
	java SearchInsertPosition

uniquebst:
	javac UniqueBST.java
	java UniqueBST
	
rightpointers:
	javac RightPointers.java
	java RightPointers

stock1:
	javac Stock1.java
	java Stock1

stock2:
	javac Stock2.java
	java Stock2

llc:
	javac LinkedListCycle.java
	java LinkedListCycle

reverseinteger:
	javac ReverseInteger.java
	java ReverseInteger
	
sametree:
	javac SameTree.java
	java SameTree

maxdepth:
	javac MaxDepth.java
	java MaxDepth

singlenumber:
	javac SingleNumber.java
	java SingleNumber

wordbreak:
	javac WordBreak.java
	java WordBreak
